### ISSUE TITLE
Error with redirect uri after initial setup

### ISSUE THREAD

**Issue by NowyQuei** [sevensolutions/traefik-oidc-auth#19]
I am using version 0.3.2 and have created a new project in Zitadel with the following settings:
- **Type**: Web
- **Auth Method**: Code
- **Redirect URIs**: `https://zitadel.myowndomain.com/oauth2/callback`

Here is my Traefik configuration:

```yaml
# traefik.yml
api:
  dashboard: true

metrics:
  prometheus:
    addRoutersLabels: true

certificatesResolvers:
  http_resolver:
    acme:
      email: "auth@myowndomain.com"
      storage: "/etc/traefik/acme_letsencrypt.json"
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

entryPoints:
  ping:
    address: ':88'
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ':443'
    http:
      middlewares:
        - default@file
        - traefik-bouncer@file

ping:
  entryPoint: "ping"

global:
  checknewversion: true
  sendanonymoususage: false

providers:
  docker:
    endpoint: "tcp://socket-proxy:2375"
    exposedByDefault: false
    network: "proxy"
  file:
    directory: "/etc/traefik/dynamic_conf"
    watch: true

log:
  level: INFO
  filePath: "/var/log/traefik/traefik.log"
  format: json
  maxSize: 10
  maxBackups: 10
  maxAge: 14

accessLog:
  filePath: "/var/log/traefik/access.log"
  format: json
  bufferingSize: 50
  fields:
    defaultMode: keep

experimental:
  plugins:
    traefik-oidc-auth:
      moduleName: "github.com/sevensolutions/traefik-oidc-auth"
      version: "v0.3.2"
```

```yaml
# traefik-compose.yml
services:
  traefik:
    container_name: ${SERVICES_TRAEFIK_CONTAINER_NAME:-traefik}
    depends_on:
      crowdsec:
        condition: service_healthy
      socket-proxy:
        condition: service_healthy
      zitadel:
        condition: service_started
    env_file: ${ABSOLUTE_PATH}/data/traefik/.env
    image: ${SERVICES_TRAEFIK_IMAGE:-traefik}:${SERVICES_TRAEFIK_IMAGE_VERSION:-3.1}
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik-dashboard.entrypoints: websecure
      traefik.http.routers.traefik-dashboard.middlewares: default@file, oidc-auth@file
      traefik.http.routers.traefik-dashboard.rule: ${SERVICES_TRAEFIK_LABELS_TRAEFIK_HOST:-HOST(`traefik.myowndomain.com`)}
      traefik.http.routers.traefik-dashboard.service: api@internal
      traefik.http.routers.traefik-dashboard.tls: "true"
      traefik.http.routers.traefik-dashboard.tls.certresolver: http_resolver
    networks:
      crowdsec:
        ipv4_address: ${SERVICES_TRAEFIK_NETWORKS_CROWDSEC_IPV4:-172.31.127.253}
      proxy:
        ipv4_address: ${SERVICES_TRAEFIK_NETWORKS_PROXY_IPV4:-172.31.191.254}
      socket_proxy:
        ipv4_address: ${SERVICES_TRAEFIK_NETWORKS_SOCKET_PROXY_IPV4:-172.31.255.253}
    ports:
      - mode: host
        target: 80
        published: "80"
        protocol: tcp
      - mode: host
        target: 443
        published: "443"
        protocol: tcp
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ABSOLUTE_PATH}/data/traefik/traefik.yml:/etc/traefik/traefik.yml
      - ${ABSOLUTE_PATH}/data/traefik/.htpasswd:/etc/traefik/.htpasswd
      - ${ABSOLUTE_PATH}/data/traefik/certs/acme_letsencrypt.json:/etc/traefik/acme_letsencrypt.json
      - ${ABSOLUTE_PATH}/data/traefik/certs/tls_letsencrypt.json:/etc/traefik/tls_letsencrypt.json
      - ${ABSOLUTE_PATH}/data/traefik/dynamic_conf:/etc/traefik/dynamic_conf:ro
      - ${ABSOLUTE_PATH}/data/traefik/log/traefik/:/var/log/traefik/
```

```yaml
# http.middlewares.oidc-auth.yml
http:
  middlewares:
    oidc-auth:
      plugin:
        traefik-oidc-auth:
          Provider:
            Url: "https://zitadel.myowndomain.com"
            ClientId: "ClientId@myowndomain.com"
            ClientSecret: "SuperSecret"
          Scopes: ["openid", "profile", "email"]
          Authorization:
            AssertClaims:
              - Name: "preferred_username"
                AnyOf: ["alice@gmail.com", "bob@gmail.com"]
              - Name: "roles"
                AllOf: ["admin", "media"]
              - Name: "user.first_name"
                AnyOf: ["Kevin"]
          Headers:
            MapClaims:
              - Claim: "preferred_username"
                Header: "X-Oidc-Username"
              - Claim: "sub"
                Header: "X-Oidc-Subject"
```

When I try to open `https://traefik.myowndomain.com/`, I get this response:

```json
{
  "error": "invalid_request",
  "error_description": "The requested redirect_uri is missing in the client configuration. If you have any questions, you may contact the administrator of the application."
}
```

The URL I see in the browser looks correct to me; it includes `...&redirect_uri=https%3A%2F%2F...`.

**Comment by sevensolutions** [comment]
Hi @NowyQuei 
the default callback url of this plugin is "/oidc/callback".
Can you try to whitelist "https://zitadel.myowndomain.com/oidc/callback" instead of "https://zitadel.myowndomain.com/oauth2/callback" in your ZITADEL client?

I you really want to use "/oauth2/callback" you can re-configure the plugin by using:
```yml
http:
  middlewares:
    oidc-auth:
      plugin:
        traefik-oidc-auth:
          CallbackUri: "/oauth2/callback"
```

Both options should be working.

**Comment by NowyQuei** [comment]
i have replaced the "/oauth2/callback" with "/oidc/callback" on the project in zitadel.
i have still the same error.

**Comment by sevensolutions** [comment]
Hmm... I'am using ZITADEL Cloud for all my tests but shouldn't make a difference here.
I tried with and without PKCE, and i also had the Development Mode disabled for the redirect Uris. Both working fine.

Do i understand that correctly?
- You trying to secure the Traefik dashboard itself using this plugin?
- You're also running ZITADEL behind the same Traefik instance?

What is the full `&redirect_uri=` part in your URL? Of course you can mask out/replace your domain.
Because this error messages basically means there is an error with the ZITADEL client config.

For example for me it's:
```
redirect_uri=https%3A%2F%2Flocalhost%3A9443%2Foidc%2Fcallback&response_type=code
```
but currently i'am testing on localhost.

I think ZITADEL is very strict about comparing the URL, so i think it's even case-sensitive.

**Comment by NowyQuei** [comment]
> Do I understand that correctly?
>
> * You're trying to secure the Traefik dashboard itself using this plugin?
> * You're also running ZITADEL behind the same Traefik instance?

Yes, you’re correct...
Maybe testing with the Traefik dashboard wasn’t the best idea. I’ve now set up Uptime Kuma as a simpler test case.

```yaml
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ${ABSOLUTE_PATH}/data/uptimekuma/data:/app/data
    networks:
      - "proxy"
    ports:
      - 3001:3001  # <Host Port>:<Container Port>
    restart: always
    labels:
      traefik.enable: true
      traefik.http.routers.uptimekuma.entrypoints: websecure
      traefik.http.routers.uptimekuma.middlewares: oidc-auth@file
      traefik.http.routers.uptimekuma.tls.certresolver: http_resolver
      traefik.http.routers.uptimekuma.rule: Host(`uptimekuma.myowndomain.com`)
```

This is the URL when the error message appears:
```
https://zitadel.myowndomain.com/oauth/v2/authorize?client_id=292156308499529732%40myowndomain&redirect_uri=https%3A%2F%2Fuptimekuma.myowndomain.com%2Foidc%2Fcallback&response_type=code&scope=openid+profile+email&state=eyJhY3Rpb24iOiJMb2dpbiIsInJlZGlyZWN0X3VybCI6Imh0dHBzOi8vdXB0aW1la3VtYS5jYWxsaG9tZS5jaC8ifQ%3D%3D
```

And I’m still seeing this error:
```json
{
  "error": "invalid_request",
  "error_description": "The requested redirect_uri is missing in the client configuration. If you have any questions, you may contact the administrator of the application."
}
```

Any insights on what might be causing this?
Do I only need to define this URL, `https://zitadel.myowndomain.com/oidc/callback`, as a Redirect URI in the Zitadel project?

In the Zitadel logs, I see a similar issue:
```
time=2024-11-12T05:50:06.327Z level=WARN msg="request error" oidc_error.description="The requested redirect_uri is missing in the client configuration. If you have any questions, you may contact the administrator of the application." oidc_error.type=invalid_request oidc_error.redirect_disabled=true status_code=400
```

Maybe I missed something in the Zitadel configuration?

**Comment by sevensolutions** [comment]
Oh i think i overlooked something.
In your original post you were hosting the dashboard on traefik.myowndomain.com.
And you're now hosting uptime kuma on uptimekuma.myowndomain.com.

The redirect uri, whitelisted in ZITADEL, must point to the same domain.
So in the first case it should be: https://traefik.myowndomain.com/oidc/callback
and for uptime kuma: https://uptimekuma.myowndomain.com/oidc/callback

I will otherwise try to reproduce the setup by myself next weekend.

**Comment by NowyQuei** [comment]
So, you’re saying I need to define each subdomain I plan to use within the Zitadel project's redirect URIs?

Currently, I only have this entry: `https://zitadel.myowndomain.com/oidc/callback`.

Does that mean this specific entry isn’t needed, or am I misunderstanding?

My idea was to protect "simple" web apps (which lack their own secure login) with a single Zitadel project. This Zitadel project should handle different subdomains, like `https://*.myowndomain.com`. For more advanced web apps like Portainer, I’d use a dedicated project.

Maybe I’ve misunderstood how Zitadel and Traefik work together for this auth flow. I thought I could create a generic project and use it across multiple subdomains.

**Comment by NowyQuei** [comment]
Got it... this seems to be the issue...
I can now see the Zitadel login screen, and login appears to be working. However, after the "successful" login, I get this error:

```
token is malformed: token contains an invalid number of segments
```

Here’s the generated URL:
```
https://traefik.myowndomain.com/oidc/callback?code=kZK17t3I-QzAue9n47CaTUJiMs4WQ2f0WggBp0z_hCw_tw&state=eyJhY3Rpb24iOiJMb2dpbiIsInJlZGlyZWN0X3VybCI6Imh0dHBzOi8vdHJhZWZpay5jYWxsaG9tZS5jaC8ifQ%3D%3D
```

Any idea what might be causing this?

**Comment by sevensolutions** [comment]
> Currently, I only have this entry: https://zitadel.myowndomain.com/oidc/callback.

Yes you can remove this one.

> My idea was to protect "simple" web apps (which lack their own secure login) with a single Zitadel project. This Zitadel project should handle different subdomains, like https://*.myowndomain.com. For more advanced web apps like Portainer, I’d use a dedicated project.

You can use a single ZITADEL project but you need to whitelist every single subdomain. Unfortunately ZITADEL doesn't allow wildcard-URLs. I think you can enable the "Development Mode" to ignore the whitelist entirely but it's not recommended.
[Here](https://github.com/zitadel/zitadel/discussions/3161) is a discussion about this.

> `token is malformed: token contains an invalid number of segments`

You need to make sure ZITADEL returns a JWT-access_token instead of an opaque token.
In your project go to "Token Settings" and select JWT.

![grafik](https://github.com/user-attachments/assets/286e783a-d01a-41f5-b785-d1c3cadc7ff2)

**Comment by NowyQuei** [comment]
Awesome! The login seems to work without any additional configuration! 

I modified the middleware for a simple test:
```yaml
http:
  middlewares:
    oidc-auth:
      plugin:
        traefik-oidc-auth:
          Provider:
            Url: "https://zitadel.myowndomain.ch"
            ClientId: "ClientId"
            ClientSecret: "SECRET"
            #UsePkce: true # Or use PKCE instead of a secret
          Scopes: ["openid", "profile", "email"]
          Authorization:
            AssertClaims:
              - Name: "roles"
                AnyOf: ["admin", "admin-users"]
```

I created this role:
![Role Creation](https://github.com/user-attachments/assets/ebc788f0-46d8-4f8a-80cc-249340305ded)

And assigned the built-in user to the role:
![User Assignment](https://github.com/user-attachments/assets/520cb7cc-c863-4924-b68a-a14a5500a46d)

After logging in, I get "Unauthorized." What did I miss this time?

**Comment by sevensolutions** [comment]
Great.

You can check the log output of traefik. It should tell you why you are not authorized.
Did you check the box "Add user roles to the access token" in ZTADEL, as shown on my screen above?
I'am also not sure how ZITADEL is calling the "roles" claim. I think i can remember it was named a little bit different.
But you should see all available claims (present in the token) in the log output.
Maybe you need to set `LogLevel: DEBUG` as shown here: https://github.com/sevensolutions/traefik-oidc-auth/blob/main/http.yml

**Comment by NowyQuei** [comment]
> Did you check the box "Add user roles to the access token" in ZTADEL, as shown on my screen above?
Yes Sir :-)

the token will only logged partially:
```
2024-11-13 21:44:34 [INFO] [traefik-oidc-auth] Reloading JWKS...
2024-11-13 21:44:34 [INFO] [traefik-oidc-auth] Exchange Auth Code completed. Token: eyJhbGciOiJSUzI1 *** REDACTED ***
2024-11-13 21:44:34 [WARN] [traefik-oidc-auth] Unauthorized. Unable to find claim roles in token claims.
2024-11-13 21:44:34 [INFO] [traefik-oidc-auth] Redirecting to OIDC provider...
2024-11-13 21:44:34 [DEBUG] [traefik-oidc-auth] AuthorizationEndPoint: https://zitadel.myowndomain.com/oauth/v2/authorize
2024-11-13 21:44:35 [INFO] [traefik-oidc-auth] Exchange Auth Code completed. Token: eyJhbGciOiJSUzI1 *** REDACTED ***
2024-11-13 21:44:35 [WARN] [traefik-oidc-auth] Unauthorized. Unable to find claim roles in token claims.
```

**Comment by sevensolutions** [comment]
Oh sorry, the available claims weren't logged in all cases. I've fixed that right now.
But i see a problem with ZITADEL here and how ZITADEL is handling user roles.
You need to request a special scope for that but roles are returned in a complex object-structure, not as an array.

What i've tried as a workaround is the following:
Create an action in ZITADEL to complement the token with all roles as a flat array.
1. In ZITADEL, go to "Actions".
2. Click new script and add the following:
```js
function flatRoles(ctx, api) {
    if (ctx.v1.user.grants === undefined || ctx.v1.user.grants.count == 0) {
        return;
    }
    
    let roles = [];
    for(const claim of ctx.v1.user.grants.grants) {
      for(const role of claim.roles)
        roles.push(role);
    }
    
    api.v1.claims.setClaim('roles', roles);
}
```
Make sure you also name the script the same name like the function name.
3. Below, select "Flow Type" "Complement Token".
4. Click Add Trigger and select trigger type "Pre Access Token Creation". Then select your script.

Now whenever an access_token gets created, it will add a simple "roles" claim containing an array of your user's roles.
You should then be able to assert it using:

```yaml
Authorization:
  AssertClaims:
    - Name: "roles"
      AllOf: ["admin"]
```

**Comment by NowyQuei** [comment]
any feedback? :-)

**Comment by WhySoBad** [comment]
I have the following snippet:
```javascript
function flatRoles(ctx, api) {
  if (ctx.v1.user.grants == undefined || ctx.v1.user.grants.count == 0) {
    return;
  }

  let grants = new Set();
  ctx.v1.user.grants.grants.forEach(claim => {
    claim.roles.forEach(role => {
    	grants.add(role);
        // grants.push(claim.projectId+':'+role)  
    })
  })

  api.v1.claims.setClaim('roles', [...grants])
}
```
which runs after the following trigger:
![image](https://github.com/user-attachments/assets/15a320a8-db6f-4033-86fb-697a659ac807)

**Comment by sevensolutions** [comment]
@NowyQuei sorry for the late reply, i'am very busy at the moment.

Yes i have tested it. I have also checked the option "Assert Roles on Authentication" in my ZITADEL project.
Maybe this is important. It says: "Role information is sent from Userinfo endpoint and depending on your application settings in tokens and other types."
I din't try it without this option checked.

Also try to use the latest version from the main branch locally. I've done a lot of rework last week.
Unfortunately it's not released yet, but i will do that as soon as possible.

**Comment by cdanis** [comment]
> So, you’re saying I need to define each subdomain I plan to use within the Zitadel project's redirect URIs?
> 
> Currently, I only have this entry: `https://zitadel.myowndomain.com/oidc/callback`.
> 
> Does that mean this specific entry isn’t needed, or am I misunderstanding?
> 
> My idea was to protect "simple" web apps (which lack their own secure login) with a single Zitadel project. This Zitadel project should handle different subdomains, like `https://*.myowndomain.com`. For more advanced web apps like Portainer, I’d use a dedicated project.
> 
> Maybe I’ve misunderstood how Zitadel and Traefik work together for this auth flow. I thought I could create a generic project and use it across multiple subdomains.

BTW, once we land PR #30 or similar, the plugin should support a single static callback domain for all apps, which will mean you won't have to list every app's redirect url in Zitadel.

**Comment by alexdelprete** [comment]
> Unfortunately ZITADEL doesn't allow wildcard-URLs.

Daniel, actually Zitadel does support wildcards in redirect_uri, it's documented [here](https://zitadel.com/docs/guides/manage/console/applications#development-mode).

I tested it and it works, so it's possible to use the Relative URL approach in traefik-oidc-auth, and use wildcards in Zitadel's redirect_uri (with dev mode turned on).

Here's my config:

![Image](https://github.com/user-attachments/assets/b794d4f7-7518-4220-8a66-823fbbe51bbc)

![Image](https://github.com/user-attachments/assets/e1ed7756-7ced-4459-8d06-8173f192fd28)

**Comment by sevensolutions** [comment]
Thx @alexdelprete, i think this is new. At least I never saw this table in the ZITADEL docs. Good to know 👍

**Comment by alexdelprete** [comment]
Maybe [documentation](https://traefik-oidc-auth.sevensolutions.cc/docs/identity-providers/zitadel) for Zitadel could be updated to reflect this, what do you think?
